version: '3.8'

services:
  web-app:
    build: .
    container_name: pasay-tax-system-container
    ports:
      - "8080:8080"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allows the container to talk to your local Ollama instance