spring.application.name=taxsystem
spring.datasource.url=jdbc:h2:mem:taxsystem_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;NON_KEYWORDS=KEY,VALUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Ollama 3.2 configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.chat.options.temperature=0.4
spring.ai.ollama.chat.options.num-predict=500
spring.ai.ollama.chat.options.max-tokens=2048
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.ollama.client.connection-timeout=2s
spring.ai.ollama.client.read-timeout=2s

google.client.id=${GOOGLE_CLIENT_ID:139040312423-lu1g1apc9b60flr8ii1ia453mkpp5ik8.apps.googleusercontent.com}